#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_COMP_BoneDynamicsStateBase

#include "Basic.hpp"

#include "BP_COMP_BoneDynamicsStateBase_classes.hpp"
#include "BP_COMP_BoneDynamicsStateBase_parameters.hpp"


namespace SDK
{

// Function BP_COMP_BoneDynamicsStateBase.BP_COMP_BoneDynamicsStateBase_C.ReceiveTick
// (Final, Native, Event, Public)
// Parameters:
// float                                   bpp__DeltaSeconds__pf                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBP_COMP_BoneDynamicsStateBase_C::ReceiveTick(float bpp__DeltaSeconds__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_COMP_BoneDynamicsStateBase_C", "ReceiveTick");

	Params::BP_COMP_BoneDynamicsStateBase_C_ReceiveTick Parms{};

	Parms.bpp__DeltaSeconds__pf = bpp__DeltaSeconds__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

