#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DebugPlayerCoord

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_DebugInputNumber_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DebugPlayerCoord.BP_DebugPlayerCoord_C
// 0x0018 (0x03D8 - 0x03C0)
class ABP_DebugPlayerCoord_C final : public ABP_DebugInputNumber_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_DebugPlayerCoord_C;              // 0x03C0(0x0008)(Transient, DuplicateTransient)
	class FString                                 Prefix;                                            // 0x03C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DebugPlayerCoord(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void OnEnter();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DebugPlayerCoord_C">();
	}
	static class ABP_DebugPlayerCoord_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DebugPlayerCoord_C>();
	}
};
static_assert(alignof(ABP_DebugPlayerCoord_C) == 0x000008, "Wrong alignment on ABP_DebugPlayerCoord_C");
static_assert(sizeof(ABP_DebugPlayerCoord_C) == 0x0003D8, "Wrong size on ABP_DebugPlayerCoord_C");
static_assert(offsetof(ABP_DebugPlayerCoord_C, UberGraphFrame_BP_DebugPlayerCoord_C) == 0x0003C0, "Member 'ABP_DebugPlayerCoord_C::UberGraphFrame_BP_DebugPlayerCoord_C' has a wrong offset!");
static_assert(offsetof(ABP_DebugPlayerCoord_C, Prefix) == 0x0003C8, "Member 'ABP_DebugPlayerCoord_C::Prefix' has a wrong offset!");

}

