#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DebugCutsceneAutoPlaySection

#include "Basic.hpp"

#include "STRUCT_CutsceneAutoPlaySection_structs.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DebugCutsceneAutoPlaySection.BP_DebugCutsceneAutoPlaySection_C
// 0x0010 (0x0048 - 0x0038)
class UBP_DebugCutsceneAutoPlaySection_C final : public UObject
{
public:
	TArray<struct FSTRUCT_CutsceneAutoPlaySection> CutsceneAutoPlaySection;                           // 0x0038(0x0010)(Edit, BlueprintVisible, ZeroConstructor)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DebugCutsceneAutoPlaySection_C">();
	}
	static class UBP_DebugCutsceneAutoPlaySection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DebugCutsceneAutoPlaySection_C>();
	}
};
static_assert(alignof(UBP_DebugCutsceneAutoPlaySection_C) == 0x000008, "Wrong alignment on UBP_DebugCutsceneAutoPlaySection_C");
static_assert(sizeof(UBP_DebugCutsceneAutoPlaySection_C) == 0x000048, "Wrong size on UBP_DebugCutsceneAutoPlaySection_C");
static_assert(offsetof(UBP_DebugCutsceneAutoPlaySection_C, CutsceneAutoPlaySection) == 0x000038, "Member 'UBP_DebugCutsceneAutoPlaySection_C::CutsceneAutoPlaySection' has a wrong offset!");

}

