#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FLIB_Renkei

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "JackGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FLIB_Renkei.BP_FLIB_Renkei_C
// 0x0000 (0x0038 - 0x0038)
class UBP_FLIB_Renkei_C final : public UBlueprintFunctionLibrary
{
public:
	static void MatineeRenkeiFadeStart(float FadeTime, class UObject* __WorldContext);
	static void MatineeRenkeiDamageReaction(class UObject* __WorldContext);
	static void MatineeRenkeiFinish(class UObject* __WorldContext);
	static void GetRenkeiManager(class UObject* __WorldContext, class ABP_RenkeiManager_C** RenkeiManager);
	static void GetMatineeTargetMonsterSize(class UObject* __WorldContext, EJackMatineeRenkeiMonsterSize* Size);
	static void MatineeRenkeiTargetLocationUpdeta(class UObject* __WorldContext);
	static void IsSpectaclShowSuccess(class UObject* __WorldContext, bool* Success);
	static void SkipMatineeRenkei(class UObject* __WorldContext);
	static void SetRenkeiCoordinateSetting(class FName LevelName, bool HiddenSilviaParadeHane, bool HiddenSilviaSaikyoHane, bool HiddenElevenParadeHane, class UObject* __WorldContext);
	static void SetReservation_SkipMatineeRenkei(class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FLIB_Renkei_C">();
	}
	static class UBP_FLIB_Renkei_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FLIB_Renkei_C>();
	}
};
static_assert(alignof(UBP_FLIB_Renkei_C) == 0x000008, "Wrong alignment on UBP_FLIB_Renkei_C");
static_assert(sizeof(UBP_FLIB_Renkei_C) == 0x000038, "Wrong size on UBP_FLIB_Renkei_C");

}

