#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IF_FacialControl

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_IF_FacialControl.BP_IF_FacialControl_C.GetFacialAnimManager
// 0x0008 (0x0008 - 0x0000)
struct BP_IF_FacialControl_C_GetFacialAnimManager final
{
public:
	class UJackFacialControlComponent*            bpp__JackFacialControlComponent__pf;               // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(BP_IF_FacialControl_C_GetFacialAnimManager) == 0x000008, "Wrong alignment on BP_IF_FacialControl_C_GetFacialAnimManager");
static_assert(sizeof(BP_IF_FacialControl_C_GetFacialAnimManager) == 0x000008, "Wrong size on BP_IF_FacialControl_C_GetFacialAnimManager");
static_assert(offsetof(BP_IF_FacialControl_C_GetFacialAnimManager, bpp__JackFacialControlComponent__pf) == 0x000000, "Member 'BP_IF_FacialControl_C_GetFacialAnimManager::bpp__JackFacialControlComponent__pf' has a wrong offset!");

}

