#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MiniMapCamera

#include "Basic.hpp"

#include "BP_MiniMapCamera_classes.hpp"
#include "BP_MiniMapCamera_parameters.hpp"


namespace SDK
{

// Function BP_MiniMapCamera.BP_MiniMapCamera_C.ExecuteUbergraph_BP_MiniMapCamera
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MiniMapCamera_C::ExecuteUbergraph_BP_MiniMapCamera(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MiniMapCamera_C", "ExecuteUbergraph_BP_MiniMapCamera");

	Params::BP_MiniMapCamera_C_ExecuteUbergraph_BP_MiniMapCamera Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MiniMapCamera.BP_MiniMapCamera_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_MiniMapCamera_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MiniMapCamera_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MiniMapCamera.BP_MiniMapCamera_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_MiniMapCamera_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MiniMapCamera_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

