#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeatherVolume

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_WeatherVolume.BP_WeatherVolume_C.ExecuteUbergraph_BP_WeatherVolume
// 0x0008 (0x0008 - 0x0000)
struct BP_WeatherVolume_C_ExecuteUbergraph_BP_WeatherVolume final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsHoukaiClearSky_HoukaiClearSky;          // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_WeatherVolume_C_ExecuteUbergraph_BP_WeatherVolume) == 0x000004, "Wrong alignment on BP_WeatherVolume_C_ExecuteUbergraph_BP_WeatherVolume");
static_assert(sizeof(BP_WeatherVolume_C_ExecuteUbergraph_BP_WeatherVolume) == 0x000008, "Wrong size on BP_WeatherVolume_C_ExecuteUbergraph_BP_WeatherVolume");
static_assert(offsetof(BP_WeatherVolume_C_ExecuteUbergraph_BP_WeatherVolume, EntryPoint) == 0x000000, "Member 'BP_WeatherVolume_C_ExecuteUbergraph_BP_WeatherVolume::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_WeatherVolume_C_ExecuteUbergraph_BP_WeatherVolume, CallFunc_IsHoukaiClearSky_HoukaiClearSky) == 0x000004, "Member 'BP_WeatherVolume_C_ExecuteUbergraph_BP_WeatherVolume::CallFunc_IsHoukaiClearSky_HoukaiClearSky' has a wrong offset!");

}

