#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PL_Title

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "JackGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass PL_Title.PL_Title_C
// 0x0008 (0x03A8 - 0x03A0)
class APL_Title_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A0(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_PL_Title(int32 EntryPoint);
	void ReceiveBeginPlay();
	void OnDisplayMessageFromSaveDataCheck(EJackUMGSaveDataCheckPoint CheckPoint);
	void ExecuteSaveDataCheckResult(TScriptInterface<class IBP_IF_SaveDataCheck_C> Sender, EJackUMGSaveDataCheckPoint CheckPoint, EJackSaveLoadResult CheckRusult);
	void OnFinishSaveDataCheck(EJackUMGSaveDataCheckPoint CheckPoint, EJackUMGSaveDataCheckResult Result);
	void ExecuteSaveDataCheck(TScriptInterface<class IBP_IF_SaveDataCheck_C> Sender, EJackUMGSaveDataCheckPoint CheckPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PL_Title_C">();
	}
	static class APL_Title_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APL_Title_C>();
	}
};
static_assert(alignof(APL_Title_C) == 0x000008, "Wrong alignment on APL_Title_C");
static_assert(sizeof(APL_Title_C) == 0x0003A8, "Wrong size on APL_Title_C");
static_assert(offsetof(APL_Title_C, UberGraphFrame) == 0x0003A0, "Member 'APL_Title_C::UberGraphFrame' has a wrong offset!");

}

