#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Hud_Balloon_002

#include "Basic.hpp"

#include "WBP_Hud_Balloon_002_classes.hpp"
#include "WBP_Hud_Balloon_002_parameters.hpp"


namespace SDK
{

// Function WBP_Hud_Balloon_002.WBP_Hud_Balloon_002_C.ExecuteUbergraph_WBP_Hud_Balloon_002
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Hud_Balloon_002_C::ExecuteUbergraph_WBP_Hud_Balloon_002(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Balloon_002_C", "ExecuteUbergraph_WBP_Hud_Balloon_002");

	Params::WBP_Hud_Balloon_002_C_ExecuteUbergraph_WBP_Hud_Balloon_002 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Hud_Balloon_002.WBP_Hud_Balloon_002_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Hud_Balloon_002_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Balloon_002_C", "Tick");

	Params::WBP_Hud_Balloon_002_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Hud_Balloon_002.WBP_Hud_Balloon_002_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Hud_Balloon_002_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Balloon_002_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hud_Balloon_002.WBP_Hud_Balloon_002_C.SetBalloon
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hud_Balloon_002_C::SetBalloon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Balloon_002_C", "SetBalloon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hud_Balloon_002.WBP_Hud_Balloon_002_C.SetAppearAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hud_Balloon_002_C::SetAppearAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Balloon_002_C", "SetAppearAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hud_Balloon_002.WBP_Hud_Balloon_002_C.SetVisibleParts
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Hud_Balloon_002_C::SetVisibleParts()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Balloon_002_C", "SetVisibleParts");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hud_Balloon_002.WBP_Hud_Balloon_002_C.SetTextureNumber
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hud_Balloon_002_C::SetTextureNumber()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Balloon_002_C", "SetTextureNumber");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hud_Balloon_002.WBP_Hud_Balloon_002_C.SetTexture
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hud_Balloon_002_C::SetTexture()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Balloon_002_C", "SetTexture");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hud_Balloon_002.WBP_Hud_Balloon_002_C.GetNumberTexture
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Digit                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   BlockIndex                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Hud_Balloon_002_C::GetNumberTexture(int32 Digit, float* BlockIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Balloon_002_C", "GetNumberTexture");

	Params::WBP_Hud_Balloon_002_C_GetNumberTexture Parms{};

	Parms.Digit = Digit;

	UObject::ProcessEvent(Func, &Parms);

	if (BlockIndex != nullptr)
		*BlockIndex = Parms.BlockIndex;
}


// Function WBP_Hud_Balloon_002.WBP_Hud_Balloon_002_C.SetAdjustScale
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hud_Balloon_002_C::SetAdjustScale()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Balloon_002_C", "SetAdjustScale");

	UObject::ProcessEvent(Func, nullptr);
}

}

