#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_Message_Sentaku_Custom_000_modern

#include "Basic.hpp"

#include "JackGame_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_Menu_Message_Sentaku_Custom_000_modern.WBP_Menu_Message_Sentaku_Custom_000_modern_C.ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern
// 0x01D0 (0x01D0 - 0x0000)
struct WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable2;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue2;                  // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable2;                    // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable3;                    // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable3;                   // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue3;                  // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable4;                    // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UJackUMGItemBase*                       CallFunc_Array_Get_Item;                           // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UJackUMGManager*                        CallFunc_GetUMGManager_ReturnValue;                // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       CallFunc_SlotAsCanvasSlot_ReturnValue;             // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UJackUMGSerifuWindowController*         CallFunc_GetSerifuWindowController_ReturnValue;    // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable4;                   // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         CallFunc_GetSelectionContent_ReturnValue;          // 0x0060(0x0010)(ZeroConstructor, ReferenceParm)
	int32                                         CallFunc_Add_IntInt_ReturnValue4;                  // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable5;                   // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue2;                // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue5;                  // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 K2Node_CustomEvent_FlagList;                       // 0x0090(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	int32                                         CallFunc_Array_Get_Item2;                          // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue3;                // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UJackUMGItemBase*                       CallFunc_Array_Get_Item3;                          // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue2;                 // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UJackUMGItemBase*                       CallFunc_Array_Get_Item4;                          // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue4;                // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue3;                 // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C5[0x3];                                       // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue2;              // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x00CC(0x0008)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable5;                    // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Array_Get_Item5;                          // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Array_Get_Item6;                          // 0x00E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Len_ReturnValue;                          // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FC[0x4];                                       // 0x00FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0100(0x0018)()
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue5;                // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue4;                 // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo;                   // 0x0128(0x0058)(HasGetValueTypeHash)
	TArray<class UJackUMGItemBase*>               K2Node_MakeArray_Array;                            // 0x0180(0x0010)(ZeroConstructor, ReferenceParm)
	struct FVector2D                              CallFunc_MeasureText_ReturnValue;                  // 0x0190(0x0008)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X;                          // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y;                          // 0x019C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FMax_ReturnValue;                         // 0x01A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A4[0x4];                                      // 0x01A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UJackUMGItemBase*                       CallFunc_Array_Get_Item7;                          // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<EJackUMGTextColorSet>                  K2Node_CustomEvent_Array;                          // 0x01B0(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	EJackUMGTextColorSet                          CallFunc_Array_Get_Item8;                          // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C1[0x3];                                      // 0x01C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue6;                // 0x01C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue5;                 // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern) == 0x000008, "Wrong alignment on WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern");
static_assert(sizeof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern) == 0x0001D0, "Wrong size on WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, EntryPoint) == 0x000000, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Length_ReturnValue) == 0x000004, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, Temp_int_Array_Index_Variable) == 0x000008, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, Temp_int_Loop_Counter_Variable) == 0x00000C, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, Temp_int_Loop_Counter_Variable2) == 0x000014, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::Temp_int_Loop_Counter_Variable2' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Add_IntInt_ReturnValue2) == 0x000018, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Add_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, Temp_int_Array_Index_Variable2) == 0x00001C, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::Temp_int_Array_Index_Variable2' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, Temp_int_Array_Index_Variable3) == 0x000020, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::Temp_int_Array_Index_Variable3' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, Temp_int_Loop_Counter_Variable3) == 0x000024, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::Temp_int_Loop_Counter_Variable3' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Less_IntInt_ReturnValue) == 0x000028, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Add_IntInt_ReturnValue3) == 0x00002C, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Add_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, Temp_int_Array_Index_Variable4) == 0x000030, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::Temp_int_Array_Index_Variable4' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Get_Item) == 0x000038, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_GetUMGManager_ReturnValue) == 0x000040, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_GetUMGManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_SlotAsCanvasSlot_ReturnValue) == 0x000048, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_SlotAsCanvasSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_GetSerifuWindowController_ReturnValue) == 0x000050, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_GetSerifuWindowController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, Temp_int_Loop_Counter_Variable4) == 0x000058, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::Temp_int_Loop_Counter_Variable4' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_GetSelectionContent_ReturnValue) == 0x000060, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_GetSelectionContent_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Add_IntInt_ReturnValue4) == 0x000070, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Add_IntInt_ReturnValue4' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, Temp_int_Loop_Counter_Variable5) == 0x000074, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::Temp_int_Loop_Counter_Variable5' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Length_ReturnValue2) == 0x000078, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Length_ReturnValue2' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Add_IntInt_ReturnValue5) == 0x00007C, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Add_IntInt_ReturnValue5' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000080, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000084, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Add_FloatFloat_ReturnValue) == 0x000088, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, K2Node_CustomEvent_FlagList) == 0x000090, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::K2Node_CustomEvent_FlagList' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Get_Item2) == 0x0000A0, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Get_Item2' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Length_ReturnValue3) == 0x0000A4, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Length_ReturnValue3' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Get_Item3) == 0x0000A8, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Get_Item3' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Less_IntInt_ReturnValue2) == 0x0000B0, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Less_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Get_Item4) == 0x0000B8, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Get_Item4' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Length_ReturnValue4) == 0x0000C0, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Length_ReturnValue4' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Less_IntInt_ReturnValue3) == 0x0000C4, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Less_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Add_FloatFloat_ReturnValue2) == 0x0000C8, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Add_FloatFloat_ReturnValue2' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_MakeVector2D_ReturnValue) == 0x0000CC, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, Temp_int_Array_Index_Variable5) == 0x0000D4, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::Temp_int_Array_Index_Variable5' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Get_Item5) == 0x0000D8, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Get_Item5' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Get_Item6) == 0x0000E8, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Get_Item6' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Len_ReturnValue) == 0x0000F8, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Len_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Conv_StringToText_ReturnValue) == 0x000100, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Max_ReturnValue) == 0x000118, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Length_ReturnValue5) == 0x00011C, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Length_ReturnValue5' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Less_IntInt_ReturnValue4) == 0x000120, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Less_IntInt_ReturnValue4' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, K2Node_MakeStruct_SlateFontInfo) == 0x000128, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::K2Node_MakeStruct_SlateFontInfo' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, K2Node_MakeArray_Array) == 0x000180, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_MeasureText_ReturnValue) == 0x000190, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_MeasureText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_BreakVector2D_X) == 0x000198, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_BreakVector2D_Y) == 0x00019C, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_FMax_ReturnValue) == 0x0001A0, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_FMax_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Get_Item7) == 0x0001A8, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Get_Item7' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, K2Node_CustomEvent_Array) == 0x0001B0, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::K2Node_CustomEvent_Array' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Get_Item8) == 0x0001C0, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Get_Item8' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Array_Length_ReturnValue6) == 0x0001C4, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Array_Length_ReturnValue6' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern, CallFunc_Less_IntInt_ReturnValue5) == 0x0001C8, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ExecuteUbergraph_WBP_Menu_Message_Sentaku_Custom_000_modern::CallFunc_Less_IntInt_ReturnValue5' has a wrong offset!");

// Function WBP_Menu_Message_Sentaku_Custom_000_modern.WBP_Menu_Message_Sentaku_Custom_000_modern_C.ChoicesColor
// 0x0010 (0x0010 - 0x0000)
struct WBP_Menu_Message_Sentaku_Custom_000_modern_C_ChoicesColor final
{
public:
	TArray<EJackUMGTextColorSet>                  Array;                                             // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
};
static_assert(alignof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ChoicesColor) == 0x000008, "Wrong alignment on WBP_Menu_Message_Sentaku_Custom_000_modern_C_ChoicesColor");
static_assert(sizeof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ChoicesColor) == 0x000010, "Wrong size on WBP_Menu_Message_Sentaku_Custom_000_modern_C_ChoicesColor");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_ChoicesColor, Array) == 0x000000, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_ChoicesColor::Array' has a wrong offset!");

// Function WBP_Menu_Message_Sentaku_Custom_000_modern.WBP_Menu_Message_Sentaku_Custom_000_modern_C.DisableChoices
// 0x0010 (0x0010 - 0x0000)
struct WBP_Menu_Message_Sentaku_Custom_000_modern_C_DisableChoices final
{
public:
	TArray<int32>                                 FlagList;                                          // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
};
static_assert(alignof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_DisableChoices) == 0x000008, "Wrong alignment on WBP_Menu_Message_Sentaku_Custom_000_modern_C_DisableChoices");
static_assert(sizeof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_DisableChoices) == 0x000010, "Wrong size on WBP_Menu_Message_Sentaku_Custom_000_modern_C_DisableChoices");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_DisableChoices, FlagList) == 0x000000, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_DisableChoices::FlagList' has a wrong offset!");

// Function WBP_Menu_Message_Sentaku_Custom_000_modern.WBP_Menu_Message_Sentaku_Custom_000_modern_C.RemoveUnuseParts
// 0x0038 (0x0038 - 0x0000)
struct WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts final
{
public:
	TArray<class FString>                         TargetArray;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
	int32                                         Max;                                               // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UJackUMGItemBase*                       CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_32[0x2];                                       // 0x0032(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue2;                // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts) == 0x000008, "Wrong alignment on WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts");
static_assert(sizeof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts) == 0x000038, "Wrong size on WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts, TargetArray) == 0x000000, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts::TargetArray' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts, Max) == 0x000010, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts::Max' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts, Temp_int_Variable) == 0x000014, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts, CallFunc_Array_Length_ReturnValue) == 0x000018, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts, CallFunc_Add_IntInt_ReturnValue) == 0x00001C, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts, CallFunc_Subtract_IntInt_ReturnValue) == 0x000020, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts, CallFunc_Array_Get_Item) == 0x000028, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000030, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts, CallFunc_Array_RemoveItem_ReturnValue) == 0x000031, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts, CallFunc_Array_Length_ReturnValue2) == 0x000034, "Member 'WBP_Menu_Message_Sentaku_Custom_000_modern_C_RemoveUnuseParts::CallFunc_Array_Length_ReturnValue2' has a wrong offset!");

}

