#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_Namae_Camera_Setting_000_modern

#include "Basic.hpp"

#include "WBP_Menu_Namae_Camera_Setting_000_modern_classes.hpp"
#include "WBP_Menu_Namae_Camera_Setting_000_modern_parameters.hpp"


namespace SDK
{

// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.ExecuteUbergraph_WBP_Menu_Namae_Camera_Setting_000_modern
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::ExecuteUbergraph_WBP_Menu_Namae_Camera_Setting_000_modern(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "ExecuteUbergraph_WBP_Menu_Namae_Camera_Setting_000_modern");

	Params::WBP_Menu_Namae_Camera_Setting_000_modern_C_ExecuteUbergraph_WBP_Menu_Namae_Camera_Setting_000_modern Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.CustomEvent_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UJackUMGSerifuWindowController*   Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             CurrentTextID                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SelectDialogIndex                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::CustomEvent_0(class UJackUMGSerifuWindowController* Sender, class FName CurrentTextID, int32 SelectDialogIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "CustomEvent_0");

	Params::WBP_Menu_Namae_Camera_Setting_000_modern_C_CustomEvent_0 Parms{};

	Parms.Sender = Sender;
	Parms.CurrentTextID = CurrentTextID;
	Parms.SelectDialogIndex = SelectDialogIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.OnItemListControl
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UJackUMGItemBase*                 InItemBase                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::OnItemListControl(class FName EventName, class UJackUMGItemBase* InItemBase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "OnItemListControl");

	Params::WBP_Menu_Namae_Camera_Setting_000_modern_C_OnItemListControl Parms{};

	Parms.EventName = EventName;
	Parms.InItemBase = InItemBase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.WidgetBPActionDelegate_Copy
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             EventTag                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::WidgetBPActionDelegate_Copy(class FName EventTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "WidgetBPActionDelegate_Copy");

	Params::WBP_Menu_Namae_Camera_Setting_000_modern_C_WidgetBPActionDelegate_Copy Parms{};

	Parms.EventTag = EventTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.SelectTextSet
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::SelectTextSet()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "SelectTextSet");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.SaveAndBack
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::SaveAndBack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "SaveAndBack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.SetAllValue
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::SetAllValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "SetAllValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.GetAllValue
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::GetAllValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "GetAllValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.SetInfoText
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::SetInfoText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "SetInfoText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.GotoTheNextMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::GotoTheNextMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "GotoTheNextMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.SetFadePanel
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::SetFadePanel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "SetFadePanel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Namae_Camera_Setting_000_modern.WBP_Menu_Namae_Camera_Setting_000_modern_C.SaveSelectedItemId
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Namae_Camera_Setting_000_modern_C::SaveSelectedItemId()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Namae_Camera_Setting_000_modern_C", "SaveSelectedItemId");

	UObject::ProcessEvent(Func, nullptr);
}

}

