#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_WorldMap_Pc_000

#include "Basic.hpp"

#include "WBP_Menu_WorldMap_Pc_000_classes.hpp"
#include "WBP_Menu_WorldMap_Pc_000_parameters.hpp"


namespace SDK
{

// Function WBP_Menu_WorldMap_Pc_000.WBP_Menu_WorldMap_Pc_000_C.ExecuteUbergraph_WBP_Menu_WorldMap_Pc_000
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_WorldMap_Pc_000_C::ExecuteUbergraph_WBP_Menu_WorldMap_Pc_000(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_WorldMap_Pc_000_C", "ExecuteUbergraph_WBP_Menu_WorldMap_Pc_000");

	Params::WBP_Menu_WorldMap_Pc_000_C_ExecuteUbergraph_WBP_Menu_WorldMap_Pc_000 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_WorldMap_Pc_000.WBP_Menu_WorldMap_Pc_000_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Menu_WorldMap_Pc_000_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_WorldMap_Pc_000_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_WorldMap_Pc_000.WBP_Menu_WorldMap_Pc_000_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_WorldMap_Pc_000_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_WorldMap_Pc_000_C", "Tick");

	Params::WBP_Menu_WorldMap_Pc_000_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_WorldMap_Pc_000.WBP_Menu_WorldMap_Pc_000_C.SetMarkerAngle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Angle                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_WorldMap_Pc_000_C::SetMarkerAngle(float Angle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_WorldMap_Pc_000_C", "SetMarkerAngle");

	Params::WBP_Menu_WorldMap_Pc_000_C_SetMarkerAngle Parms{};

	Parms.Angle = Angle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_WorldMap_Pc_000.WBP_Menu_WorldMap_Pc_000_C.SyncStartAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_WorldMap_Pc_000_C::SyncStartAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_WorldMap_Pc_000_C", "SyncStartAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_WorldMap_Pc_000.WBP_Menu_WorldMap_Pc_000_C.UpdateAnimation
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_WorldMap_Pc_000_C::UpdateAnimation(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_WorldMap_Pc_000_C", "UpdateAnimation");

	Params::WBP_Menu_WorldMap_Pc_000_C_UpdateAnimation Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_WorldMap_Pc_000.WBP_Menu_WorldMap_Pc_000_C.SyncStopAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_WorldMap_Pc_000_C::SyncStopAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_WorldMap_Pc_000_C", "SyncStopAnimation");

	UObject::ProcessEvent(Func, nullptr);
}

}

