#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Hud_Status_Icon

#include "Basic.hpp"

#include "WBP_Hud_Status_Icon_classes.hpp"
#include "WBP_Hud_Status_Icon_parameters.hpp"


namespace SDK
{

// Function WBP_Hud_Status_Icon.WBP_Hud_Status_Icon_C.ExecuteUbergraph_WBP_Hud_Status_Icon
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Hud_Status_Icon_C::ExecuteUbergraph_WBP_Hud_Status_Icon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Status_Icon_C", "ExecuteUbergraph_WBP_Hud_Status_Icon");

	Params::WBP_Hud_Status_Icon_C_ExecuteUbergraph_WBP_Hud_Status_Icon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Hud_Status_Icon.WBP_Hud_Status_Icon_C.SetBadJoutaiIjouList
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FJackUMGOddEffectStatus>  OddEffectList                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void UWBP_Hud_Status_Icon_C::SetBadJoutaiIjouList(const TArray<struct FJackUMGOddEffectStatus>& OddEffectList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Status_Icon_C", "SetBadJoutaiIjouList");

	Params::WBP_Hud_Status_Icon_C_SetBadJoutaiIjouList Parms{};

	Parms.OddEffectList = std::move(OddEffectList);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Hud_Status_Icon.WBP_Hud_Status_Icon_C.SetGoodJoutaiIjouList
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FJackUMGOddEffectStatus>  OddEffectList                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void UWBP_Hud_Status_Icon_C::SetGoodJoutaiIjouList(const TArray<struct FJackUMGOddEffectStatus>& OddEffectList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Status_Icon_C", "SetGoodJoutaiIjouList");

	Params::WBP_Hud_Status_Icon_C_SetGoodJoutaiIjouList Parms{};

	Parms.OddEffectList = std::move(OddEffectList);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Hud_Status_Icon.WBP_Hud_Status_Icon_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Hud_Status_Icon_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Status_Icon_C", "Tick");

	Params::WBP_Hud_Status_Icon_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Hud_Status_Icon.WBP_Hud_Status_Icon_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Hud_Status_Icon_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Status_Icon_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hud_Status_Icon.WBP_Hud_Status_Icon_C.SetVisible
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Hud_Status_Icon_C::SetVisible(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Status_Icon_C", "SetVisible");

	Params::WBP_Hud_Status_Icon_C_SetVisible Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Hud_Status_Icon.WBP_Hud_Status_Icon_C.SetOffsetVissible
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Offset                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Hud_Status_Icon_C::SetOffsetVissible(int32 Offset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Status_Icon_C", "SetOffsetVissible");

	Params::WBP_Hud_Status_Icon_C_SetOffsetVissible Parms{};

	Parms.Offset = Offset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Hud_Status_Icon.WBP_Hud_Status_Icon_C.ArrayInitialize
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hud_Status_Icon_C::ArrayInitialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Status_Icon_C", "ArrayInitialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hud_Status_Icon.WBP_Hud_Status_Icon_C.HiddenBuff
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hud_Status_Icon_C::HiddenBuff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Status_Icon_C", "HiddenBuff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hud_Status_Icon.WBP_Hud_Status_Icon_C.HiddenDebuff
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hud_Status_Icon_C::HiddenDebuff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hud_Status_Icon_C", "HiddenDebuff");

	UObject::ProcessEvent(Func, nullptr);
}

}

