#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_Sakusen_Settei_003_modern

#include "Basic.hpp"

#include "WBP_Menu_Sakusen_Settei_003_modern_classes.hpp"
#include "WBP_Menu_Sakusen_Settei_003_modern_parameters.hpp"


namespace SDK
{

// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.ExecuteUbergraph_WBP_Menu_Sakusen_Settei_003_modern
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Sakusen_Settei_003_modern_C::ExecuteUbergraph_WBP_Menu_Sakusen_Settei_003_modern(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "ExecuteUbergraph_WBP_Menu_Sakusen_Settei_003_modern");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_ExecuteUbergraph_WBP_Menu_Sakusen_Settei_003_modern Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.ExecuteSaveDataCheckResult
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// TScriptInterface<class IBP_IF_SaveDataCheck_C>Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// EJackUMGSaveDataCheckPoint              CheckPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EJackSaveLoadResult                     CheckRusult                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Sakusen_Settei_003_modern_C::ExecuteSaveDataCheckResult(TScriptInterface<class IBP_IF_SaveDataCheck_C> Sender, EJackUMGSaveDataCheckPoint CheckPoint, EJackSaveLoadResult CheckRusult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "ExecuteSaveDataCheckResult");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_ExecuteSaveDataCheckResult Parms{};

	Parms.Sender = Sender;
	Parms.CheckPoint = CheckPoint;
	Parms.CheckRusult = CheckRusult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.OnDisplayMessageFromSaveDataCheck
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EJackUMGSaveDataCheckPoint              CheckPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Sakusen_Settei_003_modern_C::OnDisplayMessageFromSaveDataCheck(EJackUMGSaveDataCheckPoint CheckPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "OnDisplayMessageFromSaveDataCheck");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_OnDisplayMessageFromSaveDataCheck Parms{};

	Parms.CheckPoint = CheckPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Menu_Sakusen_Settei_003_modern_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.OnFinishSaveDataCheck
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EJackUMGSaveDataCheckPoint              CheckPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EJackUMGSaveDataCheckResult             Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Sakusen_Settei_003_modern_C::OnFinishSaveDataCheck(EJackUMGSaveDataCheckPoint CheckPoint, EJackUMGSaveDataCheckResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "OnFinishSaveDataCheck");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_OnFinishSaveDataCheck Parms{};

	Parms.CheckPoint = CheckPoint;
	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.FinishSaveAsync
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SlotIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EJackSaveLoadResult                     SaveLoadResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Sakusen_Settei_003_modern_C::FinishSaveAsync(int32 SlotIndex, EJackSaveLoadResult SaveLoadResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "FinishSaveAsync");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_FinishSaveAsync Parms{};

	Parms.SlotIndex = SlotIndex;
	Parms.SaveLoadResult = SaveLoadResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.ExecuteSaveDataCheck
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// TScriptInterface<class IBP_IF_SaveDataCheck_C>Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// EJackUMGSaveDataCheckPoint              CheckPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Sakusen_Settei_003_modern_C::ExecuteSaveDataCheck(TScriptInterface<class IBP_IF_SaveDataCheck_C> Sender, EJackUMGSaveDataCheckPoint CheckPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "ExecuteSaveDataCheck");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_ExecuteSaveDataCheck Parms{};

	Parms.Sender = Sender;
	Parms.CheckPoint = CheckPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.CustomEvent_1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UJackUMGSerifuWindowController*   Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             CurrentTextID                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SelectDialogIndex                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Sakusen_Settei_003_modern_C::CustomEvent_1(class UJackUMGSerifuWindowController* Sender, class FName CurrentTextID, int32 SelectDialogIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "CustomEvent_1");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_CustomEvent_1 Parms{};

	Parms.Sender = Sender;
	Parms.CurrentTextID = CurrentTextID;
	Parms.SelectDialogIndex = SelectDialogIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.WidgetBPActionDelegate_Copy
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             EventTag                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Sakusen_Settei_003_modern_C::WidgetBPActionDelegate_Copy(class FName EventTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "WidgetBPActionDelegate_Copy");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_WidgetBPActionDelegate_Copy Parms{};

	Parms.EventTag = EventTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.CustomEvent_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UJackUMGSerifuWindowController*   Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             CurrentTextID                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SelectDialogIndex                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Sakusen_Settei_003_modern_C::CustomEvent_0(class UJackUMGSerifuWindowController* Sender, class FName CurrentTextID, int32 SelectDialogIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "CustomEvent_0");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_CustomEvent_0 Parms{};

	Parms.Sender = Sender;
	Parms.CurrentTextID = CurrentTextID;
	Parms.SelectDialogIndex = SelectDialogIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.OnItemListControl
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UJackUMGItemBase*                 InItemBase                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Sakusen_Settei_003_modern_C::OnItemListControl(class FName EventName, class UJackUMGItemBase* InItemBase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "OnItemListControl");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_OnItemListControl Parms{};

	Parms.EventName = EventName;
	Parms.InItemBase = InItemBase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.SelectTextSet
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Sakusen_Settei_003_modern_C::SelectTextSet()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "SelectTextSet");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.SaveAndBack
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Sakusen_Settei_003_modern_C::SaveAndBack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "SaveAndBack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.SetGammaValue
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Sakusen_Settei_003_modern_C::SetGammaValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "SetGammaValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.RemoveAkarusaBase
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Sakusen_Settei_003_modern_C::RemoveAkarusaBase()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "RemoveAkarusaBase");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.SetSibariGamen
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Menu_Sakusen_Settei_003_modern_C::SetSibariGamen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "SetSibariGamen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.SetVisibleSetteiWindow
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsVisible_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Menu_Sakusen_Settei_003_modern_C::SetVisibleSetteiWindow(bool IsVisible_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "SetVisibleSetteiWindow");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_SetVisibleSetteiWindow Parms{};

	Parms.IsVisible_0 = IsVisible_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_Sakusen_Settei_003_modern.WBP_Menu_Sakusen_Settei_003_modern_C.SetColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EJackUMGTextColorSet                    InColorSet                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_Sakusen_Settei_003_modern_C::SetColor(EJackUMGTextColorSet InColorSet)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Sakusen_Settei_003_modern_C", "SetColor");

	Params::WBP_Menu_Sakusen_Settei_003_modern_C_SetColor Parms{};

	Parms.InColorSet = InColorSet;

	UObject::ProcessEvent(Func, &Parms);
}

}

