#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_Namae_Mode_Select_001_modern

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "JackGame_structs.hpp"
#include "JackGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_Namae_Mode_Select_001_modern.WBP_Menu_Namae_Mode_Select_001_modern_C
// 0x0010 (0x0380 - 0x0370)
class UWBP_Menu_Namae_Mode_Select_001_modern_C final : public UJackUMGWidgetBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(Transient, DuplicateTransient)
	class UCanvasPanel*                           RootPanel;                                         // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Menu_Namae_Mode_Select_001_modern(int32 EntryPoint);
	void ExecuteSaveDataCheck(TScriptInterface<class IBP_IF_SaveDataCheck_C> Sender, EJackUMGSaveDataCheckPoint CheckPoint);
	void ExecuteSaveDataCheckResult(TScriptInterface<class IBP_IF_SaveDataCheck_C> Sender, EJackUMGSaveDataCheckPoint CheckPoint, EJackSaveLoadResult CheckRusult);
	void OnDisplayMessageFromSaveDataCheck(EJackUMGSaveDataCheckPoint CheckPoint);
	void OnFinishSaveDataCheck(EJackUMGSaveDataCheckPoint CheckPoint, EJackUMGSaveDataCheckResult Result);
	void FinishSaveAsync(int32 SlotIndex, EJackSaveLoadResult SaveLoadResult);
	void Construct();
	void WidgetBPActionDelegate_Copy(class FName EventTag);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_Namae_Mode_Select_001_modern_C">();
	}
	static class UWBP_Menu_Namae_Mode_Select_001_modern_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_Namae_Mode_Select_001_modern_C>();
	}
};
static_assert(alignof(UWBP_Menu_Namae_Mode_Select_001_modern_C) == 0x000008, "Wrong alignment on UWBP_Menu_Namae_Mode_Select_001_modern_C");
static_assert(sizeof(UWBP_Menu_Namae_Mode_Select_001_modern_C) == 0x000380, "Wrong size on UWBP_Menu_Namae_Mode_Select_001_modern_C");
static_assert(offsetof(UWBP_Menu_Namae_Mode_Select_001_modern_C, UberGraphFrame) == 0x000370, "Member 'UWBP_Menu_Namae_Mode_Select_001_modern_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Menu_Namae_Mode_Select_001_modern_C, RootPanel) == 0x000378, "Member 'UWBP_Menu_Namae_Mode_Select_001_modern_C::RootPanel' has a wrong offset!");

}

